# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c9ac62ab776e6f3260c8bc449baff39bf6cf73ee2231f8e9f6a8bbd520eb78ebcaa8a5d2fa117364d6ac5657eb422db0425342ec6ead95014574dc0126aea1c

test:
  secret_key_base: 8fcb9f35bd194872bb69e1bc5a82199a3315922ff8aed64caef2e0ee6b920d2be0f4ab6c9b8edb4a3191e857db693fc4e7a47355ca0ceb43ed75d559946d27c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
